- name: Imprimir algo
  debug:
    msg: 
      - "hostname {{ inventory_hostname }}"
      -  "os {{ ansible_os_family }}"

  
- name: Add users
  user:
    name: "{{ item }}"
    state: present 
    shell: /bin/bash
    groups: sudo
    append: yes
  loop: 
    - "andres"
    - "paco"
    - "fernando"

- name: Instalar dependencias básicas
  package:
    name: "{{ packages[ansible_os_family] }}"
    state: latest

- name: Instalar nginx
  apt:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started